### ISSUE TITLE
Could not build Objective-C module 'BrightcoveFairPlay'

### ISSUE THREAD

**Issue by ronnapa** [BrightcoveOS/ios-player-samples#13]
Currently I'm having a problem with importing BrightcoveFairPlay on my swift project. I've Added the header on the bridging file but still getting this error.

**Comment by timothyrodgers** [comment]
Hi @ronnapa. I do not see an error message included in your comment. Would you please re-post it.

FWIW, I have successfully built the Brightcove sample BasicFairPlayPlayer which is a Swift sample app. I built using the very latest framework releases after running 'pod install'.

**Comment by ronnapa** [comment]
hi @timothyrodgers, I've fixed this issue. I've removed the framework path of BrightcoveFairPlay on Header Search Paths. And now Its working. Sorry for the disturbance.

**Comment by BCjwhisenant** [comment]
I'm going to close this, based on the comments.
