### ISSUE TITLE
Did not find Video data by using ReferenceID(VideoID) in BrightCove Version 6.8.4 

### ISSUE THREAD

**Issue by Ripudaman1992** [BrightcoveOS/ios-player-samples#158]
When I update BrightCove version 8.6.4 using iOS11. I am getting some issues I did not find video data by using ReferenceID. Play & Pause functionality also not working properly

 guard let playbackService = playbackService else { return }
        playbackService.findVideo(withReferenceID: videoID, parameters: nil) { [ weak self] (video: BCOVVideo?, _, error: Error?) in
            guard let self = self else { return }
            guard let video = video else {
}

**Comment by timothyrodgers** [comment]
Ripudaman1992, you haven't provided so much as an error message. Brightcove does not provide technical support through GitHub. if you need support or want to provide feedback, please use the [support portal](https://supportportal.brightcove.com/s/login/?language=en_US) or contact your Account Manager.
