### ISSUE TITLE
How To change video url while the video is playing

### ISSUE THREAD

**Issue by serdarbakirtas** [BrightcoveOS/ios-player-samples#26]
While I change video quality so my app is crash.

I am getting new url firstly when modifying quality. For example, when the user switches from 720p video to 360p, the application gets 360p video URL. You can my code below.

![screen shot 2017-01-04 at 16 45 14](https://cloud.githubusercontent.com/assets/4365303/21644133/b33c235c-d294-11e6-81de-a7b09632fed6.png)

I would set the 360p url as follows.

![screen shot 2017-01-04 at 16 45 25](https://cloud.githubusercontent.com/assets/4365303/21644198/fb135056-d294-11e6-85b2-99479a243fa4.png)

From there the application is crash. You can see the error below.

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x600000014170 of class AVPlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x600000435ae0> (
<NSKeyValueObservance 0x6000008438d0: Observer: 0x7fd851c16c30, Key path: rate, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db760, Property: 0x6000008438a0>
<NSKeyValueObservance 0x608000656590: Observer: 0x7fd851c16c30, Key path: error, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db780, Property: 0x600000843900>
<NSKeyValueObservance 0x600000843930: Observer: 0x7fd851c16c30, Key path: status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db7a0, Property: 0x600000843960>
<NSKeyValueObservance 0x6000008439c0: Observer: 0x7fd851c16c30, Key path: currentItem, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db7c0, Property: 0x608000652570>
<NSKeyValueObservance 0x608000658480: Observer: 0x7fd851c16c30, Key path: currentItem.asset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db7e0, Property: 0x600000495e00>
<NSKeyValueObservance 0x600000845d00: Observer: 0x7fd851c16c30, Key path: currentItem.asset.duration, Options: <New: NO, Old: NO, Prior: NO> Context: 0x1043db800, Property: 0x60000049a090>
<NSKeyValueObservance 0x6000008464b0: Observer: 0x7fd851c16c30, Key path: currentItem.asset.tracks, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db820, Property: 0x600000491fd0>
<NSKeyValueObservance 0x600000846660: Observer: 0x7fd851c16c30, Key path: currentItem.asset.naturalSize, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db840, Property: 0x6000004922f0>
<NSKeyValueObservance 0x6000008469c0: Observer: 0x7fd851c16c30, Key path: currentItem.playbackBufferEmpty, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db860, Property: 0x6000006979d0>
<NSKeyValueObservance 0x600000846b40: Observer: 0x7fd851c16c30, Key path: currentItem.playbackBufferFull, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db880, Property: 0x600000697a20>
<NSKeyValueObservance 0x600000846cc0: Observer: 0x7fd851c16c30, Key path: currentItem.playbackLikelyToKeepUp, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db8a0, Property: 0x600000697a70>
<NSKeyValueObservance 0x608000840540: Observer: 0x7fd851c16c30, Key path: currentItem.forwardPlaybackEndTime, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db8c0, Property: 0x60800068b1d0>
<NSKeyValueObservance 0x6000008476b0: Observer: 0x7fd851c16c30, Key path: currentItem.seekableTimeRanges, Options: <New: NO, Old: NO, Prior: NO> Context: 0x1043db8e0, Property: 0x600000697c00>
<NSKeyValueObservance 0x6000008477a0: Observer: 0x7fd851c16c30, Key path: currentItem.status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x1043db900, Property: 0x600000697ca0>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105ca0d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010b4b021e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105d0a2b5 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000106e91ba1 NSKVODeallocate + 293
	4   libobjc.A.dylib                     0x000000010b4c4b12 _ZN11objc_object17sidetable_releaseEb + 212
	5   libsystem_blocks.dylib              0x000000010c274952 _Block_release + 102
	6   libdispatch.dylib                   0x000000010c1e512e _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010c1ca4cf _dispatch_queue_serial_drain + 1018
	8   libdispatch.dylib                   0x000000010c1cac9f _dispatch_queue_invoke + 1118
	9   libdispatch.dylib                   0x000000010c1cb047 _dispatch_queue_override_invoke + 376
	10  libdispatch.dylib                   0x000000010c1cc9dc _dispatch_root_queue_drain + 506
	11  libdispatch.dylib                   0x000000010c1cc782 _dispatch_worker_thread3 + 113
	12  libsystem_pthread.dylib             0x000000010c58b4de _pthread_wqthread + 1129
	13  libsystem_pthread.dylib             0x000000010c589341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

How can we solve it?

**Comment by sjbushell** [comment]
This isn't normal behavior - you should be able to call setVideos very reliably. The crash log looks like some code is deleting the AVPlayer prematurely (while it still has observers attached to it), and I'm not sure how that could happen inside the library.

(I'm also not sure why you'd be assigning _selectedVideoQuality) to currentPlayer.rate, assuming that's a reference to the current AVPlayer.

If you can reproduce this behavior with one of our sample apps I'd be happy to take a look at it.
