### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by maslovsa** [BrightcoveOS/ios-player-samples#93]
Hi there

I received an email from Apple:

`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.`

I checked my codebase and found only 1 place of UIWebView using.
```
> grep -r "UIWebView" . 
Binary file ./Frameworks/BrightcovePlayerSDK.framework/BrightcovePlayerSDK matches
```

**Comment by maslovsa** [comment]
Xcode Version 11.1 (11A1027)
  - Brightcove-Player-Core/dynamic (6.4.5)

**Comment by jblaker** [comment]
@maslovsa thank you for alerting us about this. The reference to UIWebView in Brightcove-Player-Core has been removed and will take effect in our next release.
